deployment:
  tasks:
    # IMPORTANT: Do NOT deploy into the same directory where cPanel checks out the repo.
    # If you deploy into the repo path, cPanel will detect a dirty working tree and refuse to deploy.
    # Override DEPLOYPATH in cPanel if needed.
    - |
      REPOROOT="$(pwd)"
      DEPLOYPATH="${DEPLOYPATH:-$HOME/repositories/backendrifas_deploy}"
      if [ "$DEPLOYPATH" = "$REPOROOT" ]; then
        echo "ERROR: DEPLOYPATH points to the repo root ($REPOROOT). Choose a different deploy directory."
        exit 1
      fi
      export DEPLOYPATH
    - /bin/mkdir -p "$DEPLOYPATH"
    # Prefer rsync if available; fallback to tar-based copy.
    - |
      if command -v rsync >/dev/null 2>&1; then
        rsync -a --delete --exclude ".git" --exclude "node_modules" --exclude ".env" ./ "$DEPLOYPATH/"
      else
        tar -cf - --exclude=.git --exclude=node_modules --exclude=.env . | (cd "$DEPLOYPATH" && tar -xpf -)
      fi
