deployment:
  tasks:
    - export DEPLOYPATH="$HOME/repositorios/backednnuevo_deploy"
    - /bin/mkdir -p "$DEPLOYPATH"
    - /usr/bin/rsync -a --delete --exclude ".git" --exclude "node_modules" --exclude ".env" ./ "$DEPLOYPATH/"
